package com.springboot.poc.domain;

// Generated Oct 17, 2015 1:38:07 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * PmCustomerLogin generated by hbm2java
 */
public class PmCustomerLogin implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -7358589560919609003L;
	private Long pmCustomerId;
	private String pmCustomerUniqueId;
	private String pmCustomerName;
	private String pmEmailId;
	private String pmMobileNo;
	private String pmLoginSource;
	private String pmHashPassword;

	private Set<PmCustomerProfile> pmCustomerProfiles = new HashSet<PmCustomerProfile>(0);

	public PmCustomerLogin() {
	}

	public PmCustomerLogin(String pmCustomerUniqueId) {
		this.pmCustomerUniqueId = pmCustomerUniqueId;
	}

	public PmCustomerLogin(String pmCustomerUniqueId, String pmCustomerName, String pmEmailId, String pmMobileNo,
			String pmLoginSource, String pmHashPassword, Set<PmCustomerProfile> pmCustomerProfiles) {
		this.pmCustomerUniqueId = pmCustomerUniqueId;
		this.pmCustomerName = pmCustomerName;
		this.pmEmailId = pmEmailId;
		this.pmMobileNo = pmMobileNo;
		this.pmLoginSource = pmLoginSource;
		this.pmHashPassword = pmHashPassword;
		this.pmCustomerProfiles = pmCustomerProfiles;
	}

	public Long getPmCustomerId() {
		return this.pmCustomerId;
	}

	public void setPmCustomerId(Long pmCustomerId) {
		this.pmCustomerId = pmCustomerId;
	}

	public String getPmCustomerUniqueId() {
		return this.pmCustomerUniqueId;
	}

	public void setPmCustomerUniqueId(String pmCustomerUniqueId) {
		this.pmCustomerUniqueId = pmCustomerUniqueId;
	}

	public String getPmCustomerName() {
		return pmCustomerName;
	}

	public void setPmCustomerName(String pmCustomerName) {
		this.pmCustomerName = pmCustomerName;
	}

	public String getPmEmailId() {
		return this.pmEmailId;
	}

	public void setPmEmailId(String pmEmailId) {
		this.pmEmailId = pmEmailId;
	}

	public String getPmMobileNo() {
		return pmMobileNo;
	}

	public void setPmMobileNo(String pmMobileNo) {
		this.pmMobileNo = pmMobileNo;
	}

	public String getPmLoginSource() {
		return this.pmLoginSource;
	}

	public void setPmLoginSource(String pmLoginSource) {
		this.pmLoginSource = pmLoginSource;
	}

	public String getPmHashPassword() {
		return this.pmHashPassword;
	}

	public void setPmHashPassword(String pmHashPassword) {
		this.pmHashPassword = pmHashPassword;
	}

	public Set<PmCustomerProfile> getPmCustomerProfiles() {
		return pmCustomerProfiles;
	}

	public void setPmCustomerProfiles(Set<PmCustomerProfile> pmCustomerProfiles) {
		this.pmCustomerProfiles = pmCustomerProfiles;
	}

}
